# Podfile

# Source Repositories
source 'https://github.com/CocoaPods/Specs.git'

# Platform min usage
platform :ios, '9.0'

# Dynamic frameworks instead of static libz
use_frameworks!


def public_pods
    pod "AFNetworking"
    pod "JSONModel", '~>1.1.2'
    pod "OHHTTPStubs"
    pod "FormatterKit"
end

def dev_pods
    pod "HCNetwork", :path => "../"

end

target 'HCNetwork_Example' do
    	public_pods
	dev_pods
end

target 'HCNetwork_Tests' do
    	public_pods
	dev_pods
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
